"""access_type

Revision ID: bb19fe862311
Revises: 9b1dfdfa0ba1
Create Date: 2025-10-11 14:02:32.242843

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb19fe862311'
down_revision = '9b1dfdfa0ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_type', sa.String(length=255), nullable=False, server_default=sa.text("'all_team_members'::character varying")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('access_type')

    # ### end Alembic commands ###
