"""add tariff table

Revision ID: 98d09e8920ac
Revises: f051706725cc
Create Date: 2025-03-31 13:20:40.566822

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d09e8920ac'
down_revision = 'f051706725cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_admins', sa.Integer(), nullable=False),
    sa.Column('bulk_upload_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tariff_pkey')
    )
    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', models.types.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('conversation_id', models.types.StringUUID(), nullable=True))
        batch_op.add_column(sa.Column('file_key', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('original_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow_conversation_variables_app_id_idx')
        batch_op.drop_index('workflow_conversation_variables_created_at_idx')
        batch_op.create_index('workflow__conversation_variables_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('workflow__conversation_variables_created_at_idx', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow__conversation_variables_created_at_idx')
        batch_op.drop_index('workflow__conversation_variables_app_id_idx')
        batch_op.create_index('workflow_conversation_variables_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('workflow_conversation_variables_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('name')
        batch_op.drop_column('original_url')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('file_key')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('tenant_id')

    op.drop_table('tariffs')
    # ### end Alembic commands ###