"""is_successfull

Revision ID: 3f2cabde9d63
Revises: 669ffd70119c
Create Date: 2025-12-02 14:06:30.416192

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2cabde9d63'
down_revision = '669ffd70119c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_successful', sa.Boolean(), server_default=sa.text('true'), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_column('is_successful')

    # ### end Alembic commands ###
