"""max_runs

Revision ID: b8f37b719fb3
Revises: 2adcbe1f5dfb
Create Date: 2025-08-04 19:19:11.555257

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f37b719fb3'
down_revision = '2adcbe1f5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_integrates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('original_url')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('size')
        batch_op.drop_column('name')
        batch_op.drop_column('file_key')
        batch_op.drop_column('mimetype')

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow__conversation_variables_app_id_idx')
        batch_op.drop_index('workflow__conversation_variables_created_at_idx')
        batch_op.create_index(batch_op.f('workflow_conversation_variables_app_id_idx'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('workflow_conversation_variables_created_at_idx'), ['created_at'], unique=False)

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_runs_per_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('max_runs_per_day')

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_created_at_idx'))
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_app_id_idx'))
        batch_op.create_index('workflow__conversation_variables_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('workflow__conversation_variables_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))

    with op.batch_alter_table('account_integrates', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###
