"""Добавилcompliance flag

Revision ID: 3e7467233541
Revises: d5af91ef3719
Create Date: 2025-09-08 05:47:46.305077

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7467233541'
down_revision = 'd5af91ef3719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_ai_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('compliance_ai_enabled')

    # ### end Alembic commands ###
