"""ocr_mode

Revision ID: 2a375d28acd0
Revises: b7d205888016
Create Date: 2025-11-17 04:59:18.973014

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a375d28acd0'
down_revision = 'b7d205888016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_method', sa.String(length=255), server_default=sa.text("'off'::character varying"), nullable=False))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_method', sa.String(length=255), server_default=sa.text("'off'::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('ocr_method')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('ocr_method')

    # ### end Alembic commands ###
