"""password updated at

Revision ID: a1672724c4b7
Revises: bb19fe862311
Create Date: 2025-11-01 13:40:22.948155

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1672724c4b7'
down_revision = 'bb19fe862311'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_updated_at', sa.DateTime(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('password_updated_at')


    # ### end Alembic commands ###
