"""move max_runs to app

Revision ID: d5af91ef3719
Revises: b8f37b719fb3
Create Date: 2025-08-07 14:35:36.670355

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5af91ef3719'
down_revision = 'b8f37b719fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_runs_per_day', sa.Integer(), nullable=True))

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('max_runs_per_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_runs_per_day', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('max_runs_per_day')

    # ### end Alembic commands ###
