"""added max vector space column to tariff

Revision ID: cd765cbd18f0
Revises: 2cdd9cbccae3
Create Date: 2025-04-02 11:45:52.790407

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd765cbd18f0'
down_revision = '2cdd9cbccae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_vs_space', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_column('max_vs_space')

    # ### end Alembic commands ###