"""add fk to tariff on tenant

Revision ID: 2cdd9cbccae3
Revises: 98d09e8920ac
Create Date: 2025-03-31 14:13:44.275973

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdd9cbccae3'
down_revision = '98d09e8920ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff_id', models.types.StringUUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('tariff_id')

    # ### end Alembic commands ###